### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by rstml** [JK0N/tensorflow-image-recognition-chrome-extension#3]
Hi, I'd like to use your work however it's not clear under which license this work is open sourced. Having permissive license such as Apache V2 would be great. You can just add from Github's templates: https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by Isetnt2** [comment]
According to the package.json file it's set with an Apache 2.0 license. 
```
"license": "Apache 2.0",

"devDependencies": {

"babel-plugin-transform-runtime": "^6.23.0",

"babel-polyfill": "^6.26.0",

"babel-preset-env": "^1.6.1",

"clang-format": "^1.2.3",

"parcel-bundler": "^1.7.1"

},



```

**Comment by JK0N** [comment]
It's Apache 2.0 but it can be changed to more permissive license if necessary. It's made as a learning experience, so do what ever you want it..

**Comment by rstml** [comment]
Thanks, Apache v2 is permissive enough for me personally. However, I believe just mentioning license in the package.json isn't enough (I'm not a lawyer). See "How to apply the Apache License to your work" section at the end of the license: https://opensource.org/licenses/Apache-2.0
